### ISSUE TITLE
Seg fault on single thread

### ISSUE THREAD

**Issue by marekkokot** [abdullah009/kcmbt_mt#2]
Hi,

Running 

``` bash
../kcmbt_mt/bin/kcmbt -i ../data/F.vesca/SRR072005.fastq -t 1
```

cause 

```
1 threads
Segmentation fault
```

I wasn't able to run KCMBT with 1 thread on any dataset I have tried. I have tried with https://github.com/abdullah009/KCMBT and it seems it works

**Comment by abdullah009** [comment]
Had some issues with parameters. Now solved. I have tested it for #thread 1, 2 & 4. Thanks.
