### ISSUE TITLE
Support for Compressed datatset.

### ISSUE THREAD

**Issue by taranglute** [abdullah009/kcmbt_mt#6]
Hi

I have quick query and it is related to support for compressed datatset.
Does  kcmbt_mt  supports compressed datatset(gzip) as I am not sure.

Regards

**Comment by abdullah009** [comment]
Hi, currently KCMBT does not support gzip file as input. I am thinking to include that soon. Thanks.

**Comment by taranglute** [comment]
Thanks :+1:
