### ISSUE TITLE
Help: KCMBT Configuration

### ISSUE THREAD

**Issue by taranglute** [abdullah009/kcmbt_mt#7]
Hi

We are working on analysis of Bioinformatics tools (related to Kmer counting) and **KCMBT** is one of them. We have gone through **readme** file and it is very helpful. As we are doing analysis so we want to be very sure about details. It would be great if you help us validating below details.

**Data structure and Sorting Algo:** Burst Tries,Radix sort
**Approach:** In-memory 
**The limit of k-size :** less than 44
**Supports online k-mer frequency retrieval :** Yes
**Supports compressed file processing :** No

Thanks
Tarang

**Comment by abdullah009** [comment]
Hi, 
I am glad to hear that you are testing with KCMBT. Currently the limit of k-size is 32. 

Thanks,
Abdullah
